### ISSUE TITLE
HelloCode

### ISSUE THREAD

**Issue by abdelhai** [devolio/devolio#1]
# Devolio HelloCode
**HelloCode** is a place where (new) developers find open source projects to work on.  
Developers can also start or share projects on **HC** and look for contributers.  

## What we need
- [ ] A page for joining as a "contributer".
- [ ] A page for adding a project.
- [ ] A page to show project details. (Maybe with comments area)
- [ ] A page for searching for projects.
- [ ] A Page for searching for potential contributers. (Part of the "Campus" project)
- [ ] A script to share new project submission to r/hellocode and gh/hellocode/issues.

**Comment by EdenSG** [comment]
You're abandoning this?

**Comment by abdelhai** [comment]
It's a different _product_ than the current Devolio Questions. I removed it form the issues, so I can focus on making DQ better.  
Any ides/input?

**Comment by EdenSG** [comment]
Ah, I see, so still part of the larger Devolio ecosystem, but not Devolio Questions. Cool.
