### ISSUE TITLE
On devolio.net, I see 500 errors when trying to view or update my portfolio

### ISSUE THREAD

**Issue by jake-billings** [devolio/devolio#32]
I created a new account using GitHub login and then tried to fill out the profile information and upload a photo. I get a 500 whenever I hit submit.

**Comment by abdelhai** [comment]
Hi @jake-billings 
Thanks for reporting, I also got some 500 errors on my side. I will fix it this weekend!
Sorry for the inconvenience.

**Comment by jake-billings** [comment]
I'm still gettings errors. Any update?

**Comment by abdelhai** [comment]
Hi @jake-billings, sorry it took so long :/
I think it was an issue with Celery and I fixed that one. Is it working now?

**Comment by abdelhai** [comment]
I guess this was an issue with the old Devolio (RIP). Sorry it didn't work well.
