### ISSUE TITLE
Add Let's Encrypt Cert

### ISSUE THREAD

**Issue by abdelhai** [devolio/devolio#5]
https://certbot.eff.org/#osx-other

**Comment by EdenSG** [comment]
Will this be running on MacOS?

**Comment by abdelhai** [comment]
@EdenSG no, Heroku. I still didn't read that much into it...

**Comment by EdenSG** [comment]
okay, i'm not really sure how heroku deals with that... doing it ourselves (with a vps or something) would probably be cheaper

**Comment by abdelhai** [comment]
You mean hosting? Then yes, VPS is way cheaper. But I wanted a super easy way to deploy changes. A VPS need some work to have similar UX.  
If you mean the LE cert, Heroku takes a `.pem` cert and there's some way to do it based on some blog posts I found.  
https://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku

**Comment by EdenSG** [comment]
Setting up a vps to automatically pull changes from a git branch is pretty easy, i think... i've never actually done it myself, but it's definitely possible. if you've got root access to the server, setting up let's encrypt is super easy (it's literally just `sudo letsencrypt auto`), and then you can just make a crontask to auto renew it... but if you feel more comfortable with heroku, it doesn't really matter

**Comment by abdelhai** [comment]
It's definately possible but not as easy and straight forward as Heroku. With Heroku I can deploy via  CLI (even before pushing to GitHub), I roll back to a working app version If the new version has crashed and a lot of nice little features that make code deployment "fun".   
I'm actually setting up an auto-deploy system at work with AWS EC2/Docker and it takes lotta of time and has *too many* moving parts :/

**Comment by EdenSG** [comment]
Haha, i see... Heroku it is, then 😛
